---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

configure_sudoers: false

dotfiles_repo: https://github.com/jochman/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .zprofile

node_version: 16
python_version: 3.8.13

homebrew_installed_packages:
  - aws-sam-cli
  - awscli
  - gh
  - localstack


homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - aws/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - slack
  - 1password
  - visual-studio-code
  - rectangle
  - iterm2
  - aws-vault
  - zoom
  - google-chrome
  - keybase
  - postman

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages:
  - name: serverless
    state: present # present/absent/latest, default: present
    version: "2.62.0" # default: N/A
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# ZSH
configure_zsh: yes

# Pyenv
configure_pyenv: yes
pyenv_python_versions:
  - version: 3.8.13

# Node & NVM
configure_nvm: yes
nvm_user:
  name: "{{ lookup('env', 'USER') }}"
nvm_rc_file_create: no