---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

configure_sudoers: false
instance_owner: "{{ instance_owner }}"

dotfiles_repo: https://github.com/jochman/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .zprofile

node_version: 16
python_version: 3.8.13

homebrew_installed_packages:
  - pyenv
  - aws-sam-cli
  - awscli
  - gh
  - poetry
  - localstack


homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - aws/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - slack
  - 1password
  - visual-studio-code
  - rectangle
  - iterm2
  - aws-vault
  - zoom
  - google-chrome
  - keybase
  - postman

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages:
  - name: serverless
    state: present # present/absent/latest, default: present
    version: "2.62.2" # default: N/A
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# ZSH
configure_zsh: yes

# Pyenv
configure_pyenv: yes
pyenv_path: "{{ home }}/pyenv"
pyenv_owner: "{{ instance_owner }}"
pyenv_global: "3.8.13"
pyenv_update_git_install: no
pyenv_enable_autocompletion: no
pyenv_python_versions:
  - "3.8.13"

# Node & NVM
configure_nvm: yes
nvm_node_version: "16"              # the node version to install via nvm
nvm_install_globally: []          # list of node versions to install globally