---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: gantsign.oh-my-zsh
      when: configure_zsh
      tags: ['zsh']
      users:
        - username: "{{ lookup('env', 'USER') }}"
    - role: agoloncser.pyenv
      when: configure_pyenv
      tags: ['pyenv']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - name: install node via nvm
      shell: "source ~/.nvm.nvm.sh && nvm install {{ node_version }} && nvm use {{ node_version }} && nvm alias default {{ node_version }}"
      when: configure_nvm
      tags: ['node']
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
