---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - name: Install node and set version
      become: yes
      become_user: root
      shell: source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm use {{ node_version }}
    - name: Install python and set version
      become: yes
      become_user: root
      shell: source ~/.pyenv/bin/pyenv && pyenv install {{ python_version }} && pyenv global {{ python_version }}
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
