---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.oh-my-zsh
  - name: avanov.pyenv
  - name: ctorgalson.nvm
    version: v2.1.0

collections:
  - name: geerlingguy.mac
